services:
  strapi:
    container_name: strapi
    platform: linux/amd64 #for platform error on Apple M1 chips
    image: node:20
    restart: unless-stopped
    working_dir: /app
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME:-strapi}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-root}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      NODE_ENV: development
    command: sh -c "npm ci && npm run develop"
    ports:
      - "1337:1337"
    networks:
      - strapi
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    container_name: database
    platform: linux/amd64 #for platform error on Apple M1 chips
    image: postgres:14
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-strapi}
      POSTGRES_USER: ${DATABASE_USERNAME:-root}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
    networks:
      - strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-root} -d ${DATABASE_NAME:-strapi}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
